---
abstract: 'easy aliasing of methods and attributes in Moose'
author:
  - 'Jesse Luehrs <doy at tozt dot net>'
  - 'Chris Prather <chris@prather.org>'
  - 'Justin Hunter <justin.d.hunter at gmail dot com>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.091440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Aliases
requires:
  Moose: 0.90
version: 0.04
